"""relation uniqueness with nulls not distinct

Revision ID: 33cad164b2a2
Revises: 592ee108ead5
Create Date: 2026-09-01 14:05:13.940173
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "33cad164b2a2"
down_revision: str | None = "592ee108ead5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Existing duplicates must go before the stricter constraint can be created.
    # They exist because PostgreSQL treated NULL dst_object_id as distinct, so
    # every re-sync inserted another copy of the same edge.
    op.execute(
        """
        DELETE FROM relation_assertion a
         USING relation_assertion b
         WHERE a.id > b.id
           AND a.repo_id = b.repo_id
           AND a.relation_type = b.relation_type
           AND a.src_object_id = b.src_object_id
           AND a.dst_object_id IS NOT DISTINCT FROM b.dst_object_id
           AND a.dst_ref IS NOT DISTINCT FROM b.dst_ref
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_relation_assertion"), "relation_assertion", type_="unique")
    op.create_unique_constraint(
        "uq_relation_assertion",
        "relation_assertion",
        ["repo_id", "relation_type", "src_object_id", "dst_object_id", "dst_ref"],
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_relation_assertion", "relation_assertion", type_="unique")
    op.create_unique_constraint(
        op.f("uq_relation_assertion"),
        "relation_assertion",
        ["repo_id", "relation_type", "src_object_id", "dst_object_id", "dst_ref"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
