"""incident resolution record and retrieval indexes

Revision ID: 592ee108ead5
Revises: e599a350bc1e
Create Date: 2026-09-01 13:44:29.172914
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "592ee108ead5"
down_revision: str | None = "e599a350bc1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Retrieval scans content_unit with ILIKE '%token%'; trigram GIN makes that usable.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_content_unit_text_trgm "
        "ON content_unit USING gin (text gin_trgm_ops)"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_resolution_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("incident_key", sa.String(length=64), nullable=False),
        sa.Column("symptom_signature", sa.Text(), nullable=True),
        sa.Column("symptom_object_id", sa.Integer(), nullable=True),
        sa.Column("symptom_evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("release_evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidate_fix_commit", sa.String(length=40), nullable=True),
        sa.Column("first_release_containing_change", sa.String(length=200), nullable=True),
        sa.Column("release_set", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("affected_constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reported_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("maintainer_confirmed", sa.Boolean(), nullable=False),
        sa.Column("release_contains_change", sa.Boolean(), nullable=True),
        sa.Column("runtime_verified", sa.Boolean(), nullable=False),
        sa.Column("workaround", sa.Text(), nullable=True),
        sa.Column("evidence_level", sa.String(length=16), nullable=False),
        sa.Column("derivation", sa.String(length=32), nullable=False),
        sa.Column("review_state", sa.String(length=16), nullable=False),
        sa.Column("conflicts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_level IN ('high','medium','low')", name="ck_incident_evidence_level"
        ),
        sa.CheckConstraint(
            "review_state IN ('derived','reviewed','rejected')", name="ck_incident_review_state"
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symptom_object_id"], ["source_object.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "incident_key", name="uq_incident_key"),
    )
    op.create_index(
        "ix_incident_repo", "incident_resolution_record", ["repo_id", "incident_key"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_content_unit_text_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_incident_repo", table_name="incident_resolution_record")
    op.drop_table("incident_resolution_record")
    # ### end Alembic commands ###
