"""initial data spine

Revision ID: e599a350bc1e
Revises:
Create Date: 2026-09-01 07:16:55.399653
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e599a350bc1e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Retrieval needs these before any table exists.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=64), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("full_name", sa.String(length=300), nullable=False),
        sa.Column("default_branch", sa.String(length=200), nullable=True),
        sa.Column("clone_path", sa.Text(), nullable=True),
        sa.Column("profile_name", sa.String(length=128), nullable=True),
        sa.Column("surfaces", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host", "full_name", name="uq_repository_host_full_name"),
    )
    op.create_table(
        "git_commit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("sha", sa.String(length=40), nullable=False),
        sa.Column("short_sha", sa.String(length=12), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("author_name", sa.String(length=200), nullable=True),
        sa.Column("authored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parents", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "sha", name="uq_git_commit_sha"),
    )
    op.create_index("ix_git_commit_short", "git_commit", ["repo_id", "short_sha"], unique=False)
    op.create_table(
        "release",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("tag_name", sa.String(length=200), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("version_norm", sa.String(length=120), nullable=True),
        sa.Column("is_prerelease", sa.Boolean(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "tag_name", name="uq_release_tag"),
    )
    op.create_index("ix_release_published", "release", ["repo_id", "published_at"], unique=False)
    op.create_table(
        "source_object",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("native_id", sa.String(length=400), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("author_association", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "kind IN ('discussion', 'discussion_comment', 'issue', 'issue_comment', "
            "'pull_request', 'release', 'commit', 'doc_file')",
            name="ck_source_object_kind",
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["source_object.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "kind", "native_id", name="uq_source_object_identity"),
    )
    op.create_index(
        "ix_source_object_number", "source_object", ["repo_id", "kind", "number"], unique=False
    )
    op.create_index(
        "ix_source_object_repo_kind", "source_object", ["repo_id", "kind"], unique=False
    )
    op.create_index(
        "ix_source_object_updated",
        "source_object",
        ["repo_id", "kind", "source_updated_at"],
        unique=False,
    )
    op.create_table(
        "sync_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("watermark", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_full_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("objects_seen", sa.BigInteger(), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "status IN ('unknown','complete','degraded','stale','failed','running')",
            name="ck_sync_status",
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "source", name="uq_sync_state"),
    )
    op.create_table(
        "object_revision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["object_id"], ["source_object.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_id", "body_hash", name="uq_object_revision_body"),
    )
    op.create_index(
        "ix_object_revision_current", "object_revision", ["object_id", "is_current"], unique=False
    )
    op.create_table(
        "relation_assertion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("relation_type", sa.String(length=48), nullable=False),
        sa.Column("src_object_id", sa.Integer(), nullable=False),
        sa.Column("dst_object_id", sa.Integer(), nullable=True),
        sa.Column("dst_ref", sa.String(length=400), nullable=True),
        sa.Column("derivation", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("confidence IN ('high','medium','low')", name="ck_relation_confidence"),
        sa.CheckConstraint(
            "derivation IN ('github_native','git_deterministic','text_explicit','inferred')",
            name="ck_relation_derivation",
        ),
        sa.ForeignKeyConstraint(["dst_object_id"], ["source_object.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["src_object_id"], ["source_object.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repo_id",
            "relation_type",
            "src_object_id",
            "dst_object_id",
            "dst_ref",
            name="uq_relation_assertion",
        ),
    )
    op.create_index(
        "ix_relation_dst",
        "relation_assertion",
        ["repo_id", "dst_object_id", "relation_type"],
        unique=False,
    )
    op.create_index(
        "ix_relation_src",
        "relation_assertion",
        ["repo_id", "src_object_id", "relation_type"],
        unique=False,
    )
    op.create_table(
        "release_containment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("contains", sa.Boolean(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["release_id"], ["release.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("release_id", "commit_sha", name="uq_release_containment"),
    )
    op.create_index(
        "ix_release_containment_commit",
        "release_containment",
        ["repo_id", "commit_sha"],
        unique=False,
    )
    op.create_table(
        "content_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("unit_type", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("lang", sa.String(length=16), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["object_id"], ["source_object.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["revision_id"], ["object_revision.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("revision_id", "seq", name="uq_content_unit_seq"),
    )
    op.create_index("ix_content_unit_object", "content_unit", ["object_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_content_unit_object", table_name="content_unit")
    op.drop_table("content_unit")
    op.drop_index("ix_release_containment_commit", table_name="release_containment")
    op.drop_table("release_containment")
    op.drop_index("ix_relation_src", table_name="relation_assertion")
    op.drop_index("ix_relation_dst", table_name="relation_assertion")
    op.drop_table("relation_assertion")
    op.drop_index("ix_object_revision_current", table_name="object_revision")
    op.drop_table("object_revision")
    op.drop_table("sync_state")
    op.drop_index("ix_source_object_updated", table_name="source_object")
    op.drop_index("ix_source_object_repo_kind", table_name="source_object")
    op.drop_index("ix_source_object_number", table_name="source_object")
    op.drop_table("source_object")
    op.drop_index("ix_release_published", table_name="release")
    op.drop_table("release")
    op.drop_index("ix_git_commit_short", table_name="git_commit")
    op.drop_table("git_commit")
    op.drop_table("repository")
    # ### end Alembic commands ###
