"""package manifests and mention roles

Revision ID: f10b0a5f098e
Revises: ef5cca6e9e3f
Create Date: 2026-09-02 16:23:21.007274
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f10b0a5f098e"
down_revision: str | None = "ef5cca6e9e3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Also force a signature rebuild.

    Package mentions now carry a context-derived role, so `subject_package`
    rows mined by the previous extractor mean something different: they were
    assigned by token shape, not by whether the sentence said the package
    failed or was merely used. They are deleted and the recorded extractor
    version cleared, which makes `require_fresh_signatures` refuse to diagnose
    until `repo-troubleshooter signatures <repo> --rebuild` has run.
    """
    op.execute("DELETE FROM symptom_signature")
    op.execute(
        "UPDATE sync_state SET stats = stats - 'extractor_version' WHERE source = 'signatures'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_manifest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=120), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("is_workspace_root", sa.Boolean(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "path", name="uq_package_manifest_path"),
    )
    op.create_index(
        "ix_package_manifest_name", "package_manifest", ["repo_id", "name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_package_manifest_name", table_name="package_manifest")
    op.drop_table("package_manifest")
    # ### end Alembic commands ###
