"""symptom signatures

Revision ID: f13e71155147
Revises: 33cad164b2a2
Create Date: 2026-09-01 15:40:39.518529
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f13e71155147"
down_revision: str | None = "33cad164b2a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "symptom_signature",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("feature_kind", sa.String(length=16), nullable=False),
        sa.Column("feature_value", sa.String(length=300), nullable=False),
        sa.Column("derivation", sa.String(length=32), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "feature_kind IN ('error','structural','behavior','component','cause')",
            name="ck_symptom_signature_kind",
        ),
        sa.ForeignKeyConstraint(["object_id"], ["source_object.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "object_id", "feature_kind", "feature_value", name="uq_symptom_signature"
        ),
    )
    op.create_index(
        "ix_symptom_signature_lookup",
        "symptom_signature",
        ["repo_id", "feature_kind", "feature_value"],
        unique=False,
    )
    op.create_index("ix_symptom_signature_object", "symptom_signature", ["object_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_symptom_signature_object", table_name="symptom_signature")
    op.drop_index("ix_symptom_signature_lookup", table_name="symptom_signature")
    op.drop_table("symptom_signature")
    # ### end Alembic commands ###
